electron/main.js

Fixes "Cannot find module '../dialog'" by returning after checking if an
instance already exists instead of allowing the code to continue and try
to make new instance.

fix error when opening a new instance when one already exists

---

tasks/dev.js

done should be passed to karma server, not called.
This fixes an error causing a blank screen on startup for native Linux builds (untested on windows).
This error does not occur when starting through `npm start` only the native builds.
Building now takes much longer, this is a good thing I think, as it appears the tests were not running before due to the done() function being called before being passed to the karma server.

fix blank screen on startup

---

app-src/scripts/main/global-services/projects-s.js

This bug stil occurs when when creating a project for the first
time (The first clone is intentional although it will keep cloning and
will presist until restarting the program).
The current workaround is to create your first project then instantly
restart the program. After this the bug should be gone forever.
It's not perfect but it's all I can get working right now. #41 should
probably stay open for now.

fix: partially fix 'creating a new project clones the old one'

---

src/app/features/worklog/worklog-export/worklog-export.component.ts

When exporting grouped by work log:
- Don't show parent's time spent (to avoid incorrect sums)
- Show relative estimated time (based on share of the work log in the
task's time spent)
Resolves remarks from #195 
Finally implements #162

Fix minor issues with grouped exports

---

src/app/features/project/project.service.ts

Hi,
I had this issue when I opened the app locally, I cleared the storage but this issue continued:
```
Error: Uncaught (in promise): TypeError: Cannot add property __modelVersion, object is not extensible TypeError: Cannot add property __modelVersion, object is not extensible at migrateProjectState (http://localhost:4200/main.js:21566:84) at ProjectService. (http://localhost:4200/main.js:22064:129) at step (http://localhost:4200/main.js:21985:23) at Object.next (http://localhost:4200/main.js:21966:53) at fulfilled (http://localhost:4200/main.js:21957:58) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:10397:26) at Object.onInvoke (http://localhost:4200/vendor.js:91089:33) at …
```

fixing `object is not extensible`

---

electron/main-window.ts
package.json

I'm not able to test the multi-monitor behavior of this at the moment but if it doesn't work as desired then it can either be fixed upstream in the [electron-window-state](https://github.com/mawie81/electron-window-state) package.

Resolves #102: Save and restore window size and position

---

src/app/core-ui/shortcut/shortcut.service.ts

Hello @johannesjo 
So, on MacOS I'm accustomed to using `Cmd+,` as a shortcut for the preferences page. After manually setting the shortcut I noticed that it actually brought me to the project page.
I tracked down the problem to a wrong routing. As it can be seen here:
https://github.com/johannesjo/super-productivity/blob/master/src/app/app.routes.ts#L17
the actual route is `config`, not `settings`. Hoping not to have misinterpreted the intended behaviour this simple PR fix this.

Fix: preferences shortcut not working

---

package.json

Hello @johannesjo 
This a minor Quality of Life improvement that you may want to investigate a little before merging (or not).
On Mac both the application title and the application bundle are spelled `superProductivity`, which is a little ugly and breaks the consistency.
As a solution I found that adding a `productName` key gets the job done. 
||Title Bar|App Bundle|
|---|---|---|
|Before|![Schermata 2020-07-12 alle 17 52 40](https://user-images.githubusercontent.com/6209647/87425049-51db6b00-c5dd-11ea-89fc-79714690aec1.png)|![Schermata 2020-07-12 alle 17 55 25](https://user-images.githubusercontent.com/6209647/87425054-52740180-c5dd-11ea-9df1-1bb97bfa1530.png)|
|After|![Schermata 2020-07-12 alle 17 22 09](https://user-images.githubusercontent.com/6209647/87425044-5011a780-c5dd-11ea-8a52-6 …

Add product name key to package.json

---

src/assets/i18n/zh.json

The former translation for "MISC" seemed just like Google Translate. I polished it. I will continue to polish the other parts when I am available.
之前“MISC”的翻译，一股子谷歌机翻味，我给润了色。有时间我也会把其他部分润色。

Better translation for "MISC"

---

src/app/features/config/keyboard-input/keyboard-input.component.ts

Use the escape key to remove bound keyboard shortcuts. I also thought that removing the focus would benefit UX.
I have tested the following:
* Removing a shortcut and the shortcut is not applied anymore.
* Setting a new shortcut afterwards again.
closes issue #497

fix: delete a keyboard shortcut

---

src/app/features/issue/providers/jira/jira-api.service.ts
src/app/util/strip-trailing.ts

Strips possible trailing slash in the host path of jira.
I tested the `stripTrailing` itself, but since I don't have an access to jira itself, I could not test this part.
I was not sure about the handling of `cfg.host` possibly being `null`, so I used `'null'` as a fallback (as would have happened before).
fixes issue #622

fix: strip trailing jira host slash

---

build/linux/PKGBUILD_template

This will fix an error/warning message because of the lack of MD5 Checksum for downloaded files during the package build (The .deb file)

Explictly skip the MD5sums

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

- Comment was bleeding into heading, fix by adding a new line before the comment.
Fixes an issue where the HTML comment started on the same line as the heading. If people don't change that manually, the `<--` is being rendered as part of the heading.
n/a

Fix feature request template

---

electron/indicator.ts
electron/main.ts

This PR adds new cmdline arg (`--force-dark-tray`). Not sure how it should be tested. I've tested it on my PC (Fedora 33, Gnome 3) by adding new CLI arg to the npm start script. Let me know if it needs any additional tests.
Fix https://github.com/johannesjo/super-productivity/issues/741

fix: add cmdline switch to force tray icons for dark mode #741

---

src/app/features/issue/providers/jira/jira-view-components/dialog-jira-add-worklog/dialog-jira-add-worklog.component.ts

bug: Adding worklog to Jira is converting starts to Zulu time #757
_convertTimestamp() is replaced. Previous version used GMT time to convert it to string and removed last char ('Z' = Zulu time). The change uses moment to be able to show timestamp in local timezone. 
#757

bug: Adding worklog to Jira is converting starts to Zulu time #757

---

Dockerfile

This allows for a custom port to be exposed.
Port 80, the currently default port is in use on the NAS I use and I'm experiencing a crash when I try to override the port manually

Allow port to be customized in dockerfile

---

src/app/features/issue/providers/caldav/caldav.const.ts

This is necessary as there is a caldav config already for every new
project even if caldav was never set up for the project. This causes a
miconfiguration-warning on every issue-add.

fix(issues): Disable caldav issue search by default

---

src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts

Currently an empty string value for `gitlabBaseUrl` breaks polling and other gitlab api requests, this is due to a condition it should fail as a falsey value, this change corrects that.
Fixes #926

Use truthy check as condition for gitlabBaseUrl url construction

---

src/app/features/issue/providers/caldav/caldav-client.service.ts
src/app/features/issue/providers/caldav/caldav-common-interfaces.service.ts
src/app/features/issue/providers/caldav/caldav-issue/caldav-issue.model.ts

It seems that last changed is not always available. As the issue model
expects a number for a change-identification attribute this simply
computes a hash over the etag value, which should change on every
content-change if the caldav service behaved correctly.
Resolves #952

fix(issues): do not rely on caldav last-changed

---

src/app/features/pomodoro/pomodoro.service.ts

Use SoundConfiguration#volume to set the tick volume of pomodoro, getthe code idea from commented code in play-done-sound.
Fixes #956

[fix] Use volume setting for pomodoro tick sound.

---

src/app/features/pomodoro/store/pomodoro.effects.ts

If the task is manually paused, the progress bar in the windows taskbar will show yellow / orange instead of green.
None known
Need help on writing testing (if required)

feat(pomodoro): Added pause status for windows taskbar

---

src/app/imex/sync/web-dav/web-dav-api.service.ts
src/app/imex/sync/web-dav/web-dav-sync.service.ts

This fixes issues with the handling of WebDAV headers:
- Don't attempt to set Content-Length manually (as browsers forbid this and set it automatically; Axios does the right thing, apparently)
- Correct handling of ETAG header, which is not always present in PUT or PROPFIND requests.
#1199 and #1197

Fix handling of WebDAV headers

---

.github/workflows/build-publish-to-aur-on-release.yml

Looks like the AUR deployment action failed. If I'm right, this error should be fixed using the last version of the action. Can we give it a try?

Update AUR deployment action

---

src/app/features/tasks/store/task-electron.effects.ts

For task with no time estimate, the taskbar will show an indeterminate moving green indicator instead of "full" bar.
None that I know of

feat(TaskBar): Add indeterminate state for tasks with no time estimate

---

src/app/features/tasks/task/task.component.mixins.scss
src/app/features/tasks/task/task.component.scss

This removes the unused isHostFocus mixin and refactors a part that used to mess up during
`yarn buildAllElectron:prod && yarn electron-builder`
For me now this builds just fine.

refactor(Task): remove isHostFocus mixin

---

src/app/features/search-bar/search-bar.component.ts
src/app/features/search-bar/search-bar.model.ts

In fact, there is a chance for a task not to have neither a tag nor a project. Example: a subtask without a project.
By design subtasks don't inherit their parent's tags.
This will now search for the parent and use its tags instead.
It will also use a fallback help-icon if still no context can be found. This way the search function won't break.
#1325

fix(search): can't read property 'icon' of undefined #1325

---

src/app/core-ui/shortcut/shortcut.service.ts

If I press Shift+V, I currently get a message that says "Shift+N pressed, but open bookmarks shortcut is only available when in project context".
This should fix the message to display "Shift+V" instead. I haven't tested it though.

Fix shortcut in message about bookmark

---

README.md

First time proposing a change. The user data path in Windows is located in `%APPDATA%`, not `%LOCALAPPDATA%` (the latter contains a generic update folder).
New path (Windows): `%appdata%\superProductivity`
States the correct location of the user directory on Windows.
Search through the open issues show nothing.

docs: Correct Windows User Data Path in README.md

---

src/assets/i18n/de.json

I noticed a upper/lower case issue in the German translation for 'Pomodoro TImer'.
Replaced by 'Pomodoro Timer'.
no issue created.
- [ n/a] New functionality includes testing.
- [ n/a] New functionality has been documented in the README if applicable.

i18n/de: fix typo in 'Pomdoro Timer'

---

src/app/features/issue/providers/github/github.const.ts
src/app/features/issue/providers/gitlab/gitlab.const.ts
src/app/features/issue/providers/open-project/open-project.const.ts

When creating a project from github, gitlab or OpenProject the access Tokens were shown in clear text. I Changed the input field type to password fields.
[#1605 hiding security keys in settings](https://github.com/johannesjo/super-productivity/issues/1605)

fix: Hide security keys in settings #1605

---

src/app/features/timeline/ical/get-relevant-events-from-ical.ts

Defaults DTEND to DTSTART if DTEND is missing. This is compliant with RFC 2445. See https://github.com/johannesjo/super-productivity/issues/1814#issuecomment-1008132824 for a detailed explanation.
#1814 
I do not code in javascript/typescript, so I do not have the kit available to test this.
Not needed.

default dtend to dtstart if dtend is missing per RFC

---

src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts

I have a project/group in gitlab that has more than 200 issues. I noticed that only 100 are imported. I looked into the api and there is a paging functionality so I tried my best on implementing this. As with my first pull request I am still not fluent in this whole typescript/reactive-programming so I am not certain that this is the best or even a good way of implementing this but 
this seems to work for my dataset.
For the same reason I don't feel confident in wrinting tests for this functionality.
Please feel free to suggest improvements.

Implement gitlab paging for big issue lists

---

src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts

Changes sendPaginatedRequest for Gitlab API paginated requests to use query-string package for better manage the query parameters
Closes  #1923

Change sendPaginatedRequest for Gitlab API paginated requests

---

src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts

Fix a small problem with parsing the data. Every pagination call was parsed as an issue object when it shouldn't, because it could be a comment.
https://github.com/johannesjo/super-productivity/issues/1970

fix pagination requests in gitlab

---

src/app/core-ui/main-header/main-header.component.html
src/app/core/banner/banner/banner.component.scss
src/app/t.const.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Follow-up to #2013 by adding labels to Pomodoro main header buttons but also fixing their overlapping interaction with the header UI element.
This adds two new translation strings which I took care to add in English and French:
- `F.POMODORO.S.SESSION_SKIP`
- `F.POMODORO.S.SESSION_END`
None

Pomodoro controls labels

---

src/app/features/tasks/task/task.component.scss
src/styles/components/_overwrite-material.scss

this merge will make minor changes to scss to center button icons on android
this will resolve open issue [#1975](https://github.com/johannesjo/super-productivity/issues/1975#issue-1176152299)
- [ X ] New functionality includes testing.
I tested on desktop and mobile(samsung a51) using firefox, chrome, and gnome web. I didn't test using an .apk build because I'm still noob so sorry about that.
here are some before and afters from the mobile tests
<details>
<summary>before</summary>
<img
src="https://user-images.githubusercontent.com/86887236/163917597-f5df8eb4-a9cb-4749-b9e8-dbac16b1aaa2.jpg"
alt=""
style="height: 650px;"
/><img
src="https://user-images.githubusercontent.com/86887236/163917794-9adba547-7412-48b1-a9fa-ed915451c174.jpg"
alt=""
style="height: 650px;"
/>
</details>
<details> …

Fix/android center icons #1975

---

src/app/ui/better-drawer/better-drawer-container/better-drawer-container.component.ts

The margin is set regarding that the page is LTR so `margin-right` is set to `-40%`. This was true also when page was RTL and it caused showing the notes sidebar behind the tasks list. 
Changed the changing margin to margin-left when the layout is rtl to fix this.

fix: move notes sidebar to left when rtl

---

src/app/features/quick-history/quick-history.component.ts
src/app/features/worklog/util/map-archive-to-worklog-weeks.ts
src/app/features/worklog/util/map-archive-to-worklog.ts
src/app/features/worklog/worklog-week/worklog-week.component.ts
src/app/features/worklog/worklog.service.ts
src/app/util/get-week-number.spec.ts
src/app/util/get-week-number.ts
src/app/util/get-weeks-in-month.spec.ts
src/app/util/get-weeks-in-month.ts

we can set the first day of week to what we want, but the value is not respected in worklog and quick history.

feat: respect first day of week in reports

---

src/app/features/project/store/project.selectors.ts

This is a small change to hide projects from the "Add to project" context menu that are marked as `isHiddenFromMenu`
- https://github.com/johannesjo/super-productivity/issues/2077

Hide projects that are marked as hidden from "Add To Project" context menu

---

src/app/features/procrastination/procrastination.component.html
src/app/features/procrastination/procrastination.component.scss

Change sync icon rotation from clockwise to counter-clockwise. This way,
the icon rotates in the same direction that the arrows are pointing.

style(procrastination): Mirror Sync Icon

---

src/app/features/tasks/task-additional-info/task-additional-info.component.html
src/app/features/tasks/task-additional-info/task-additional-info.component.scss

This PR adds the completed date of a task to the Additional Info panel. If the completed date doesn't exist, nothing is added.
I will add tests later if applicable.
resolves #2155

Add done date to Additional Info panel if exist

---

electron/indicator.ts

I changed the code based on the discussion we had [here](https://github.com/johannesjo/super-productivity/issues/1014#issuecomment-1226844339).
Now it will use dark colors if its linux or its windows and not windows 11.
resolves #1014

Use dark colors based on os and os version

---

src/app/ui/ui.module.ts
src/styles/page.scss

Addresses the rendered markdown issues where: 
>     * the quote isn't very lisible (despite the left offset); it could contain a vertical bar
> 
>     * the second list (with checkboxes) is oddly displayed
---
First issue -> Added a vertical bar on the left side of quote with blockquote tag styling on [src/styles/page.scss](https://github.com/johannesjo/super-productivity/blob/a0ce0e549ea56593cc1ced115bf220772f6e203f/src/styles/page.scss) as this will also be applied to components that has a **markdown** directive
Second issue -> Due to every element that had been appended by paragraph tag on markdown render
``` HTML
<li style="list-style: none;">
<p>
<input checked="" disabled="" type="checkbox"> 
</p>
<p>
<a target="_blank" href="https://www.e-marketing.fr/Thematique/academie-1078/fiche …
```

fix(markdown renderer): quotes & lists display issue

---

src/styles/components/date-time-picker-schedule.scss

This small style change makes the datetime picker more coherent by darkening the selected reminder date instead of the first focused one.
- #2247

Make the datetime picker more coherent by darkening the selected reminder date

---

electron-builder.yaml

Add Win32/ARM64 topology to electron-builder and produces ARM64 builds for Windows.
`artifactName` is added to produce installer/portable executable per arch, otherwise nsis and portable creates a universal one with size doubled, see https://github.com/electron-userland/electron-builder/pull/5718
This is how app-builds look now:
- superProductivity-7.12.1.exe: universal portable
- superProductivity-7.12.1-arm64.exe: ARM64 portable
- superProductivity-7.12.1-x64.exe: X64 portable
- superProductivity Setup 7.12.1.exe: universal installer
- superProductivity Setup 7.12.1-arm64.exe: ARM64 installer
- superProductivity Setup 7.12.1-x64.exe: x64 installer
```
npm run dist:only
> superProductivity@7.12.1 dist:only
> electron-builder
• electron-builder  version=23.3.3 os=10.0.22621
• loaded …
```

Produce Win32/ARM64 packages

---

src/polyfills.ts

Add a polyfill in `src/polyfills.ts` for compatibility with Chrome <= 69 (default WebView on Android <= 9.0). This bug also happens with desktop versions of Chrome, not only mobile.
In practice, this PR adds compatibility for Android 9.0 and 8.1 out of the box (whereas before, only Android 10+ were compatible out of the box, without updating Chrome first). This PR does not change anything for Android 6.0+ with an updated Chrome browser, as updating Chrome always restore compatibility with `super-productivity` (tested on Android 7.0+ in AVD emulator, could not test Android 6.0 because of a lack of Play Store but it should be the same).
Fixes #2451, fixes https://github.com/johannesjo/super-productivity-android/issues/34 .
Tested on (AVD emulator, default Chrome browser):
Note that updating …

Compatibility with Chrome <= 69 (default WebView on Android <= 9.0)

---

src/assets/i18n/ru.json

I made it so that the texts with colors look the same.
I also fixed a mistake in the "Markdown" translation (it shouldn't translate into Russian).

fix(i18n): some fixes for russian translate

---

src/assets/i18n/pt.json

In Brazil, when we talk about a pomodoro timer we don't translate the word "pomodoro" to "tomate". To keep consistency I've changed the word "tomate" to "pomodoro" just as we have in the whole file

Updated "tomate" word to "pomodoro"

---

package.json

Added new build task to generate version for Apple M1 processors
#2503 
- [ x] New functionality includes testing.
- [ x] New functionality has been documented in the README if applicable.

chore: added new task to build versions for Apple's M1 processors

---

Dockerfile

Docker image builds have been broken since 3895c130b830ade27b649867a1c1867d3de7cc3f ([v7.11.6](https://github.com/johannesjo/super-productivity/actions/runs/2932989100)). Changing the version of node used in Dockerfile to 16 as in the other build workflows solves this problem.

build: update node version in Dockerfile

---

src/assets/i18n/de.json

This is wrongly translated as "should be lower than", which results in funny error messages about "should be lower than 1" when you enter 0:
Now translated it as "should not be lower than" similar to the max one, so than 1 in our example is still valid. "should be larger than or equal" would also be possible, but I deemed this to be unnecessary long and wordy.
N/A

Fix wrong translation

---

src/app/features/pomodoro/store/pomodoro.effects.ts

If manual pomodoro break confirmation is required, do not stop time tracking before the user actually starts the break.
I did not made this as a optional feature as
1) I do not see the point.
2) I barely know how to code in Typescript and those two lines took me one hour.
Closes #2504 and addresses #2587.

Do not stop time tracking before manual confirmation

---

e2e/src/work-view.e2e.ts
src/app/features/tasks/task/task.component.ts

Hello there.
These changes should help resolve how the application focuses the first task of a task list if the last subtask of another task is marked as done via the tick button. The resulting behaviour should put it in line with how the focus travels when resolving the subtask using a keyboard shortcut instead. 
I've also added an E2E test to cover this particular scenario. I'm not all too familiar with how this works with Nightwatch, but I gave it my best shot.
As an aside, there's another usability niggle (opinionated) I've noticed, but I don't have any good ideas for how to improve it.
If one marks a task with subtasks as done, then the focus doesn't move to the next sibling task in the same list. Underneath the hood, the application tries to shift the focus to the first subtask. …

fix: focus after marking last subtask done (#2795)

---

src/assets/i18n/fr.json

Wrong translation Remote was translated remote-control
Change for the correct expression

Wrong translation : remote-télécommande

---

src/app/features/tasks/add-task-bar/add-task-bar.component.html

Closes #2874
Disables spellchecking in Add Task Bar Component, fixes issues with tags and non-english words being highlighted as wrong.

Disable spellcheck in Add Task Bar Component

---

src/app/core-ui/main-header/main-header.component.html

Show the title of the simple counter when hovering over the icon.

fix: show simple counter title on hover #2660

---

src/app/imex/sync/web-dav/web-dav-api.service.ts
src/app/imex/sync/web-dav/web-dav-sync.service.ts

While checking the bundle size (4.2ish MB) I wanted to try out a simple improvement and decided to lazy load webdav as an example, with that 100kb are now lazy-loaded only when webdav is actually used, sure it might not be a lot in comparison to the 4.2mb but each byte counts 😬 
Also while changing it to lazy-load I saw it was missing some types, now thats added as well.
While testing it I came across the 404 Error, so I had to fix that haha
-  fixes #1883

Lazy Load WebDAV and fix NO_REMOTE_DATA error

---

src/app/core-ui/main-header/main-header.component.html
src/app/core-ui/main-header/main-header.component.ts
src/app/features/tasks/task/task.component.html
src/app/features/tasks/task/task.component.scss
src/app/features/tasks/task/task.component.ts

I have implemented the feature would like to get initial feedback. 
Added keybind previews to the main task context menu and multiple tooltips in the main task window. 
The keybindings in the context menu are aligned to the right and have a lower transparency. 
Currently all keybindings are surrounded by ```[]```.
Nothing will be visible when the key is unbound.
Right now the design has some issues, like the arrow being on the right. So I would welcome any ideas for improving the design.
#3063

feat: Add current keyboard shortcuts to app menu's #3063

---

src/app/imex/sync/web-dav/web-dav-api.service.ts

Found an issue using webDAV, debugged and discovered that the sync data field changed from file to folder. Corrected the relevant code.

fix(webDAV): update config entity

---

src/app/features/tasks/store/task.actions.ts

Change the enum value of AddNewTagsFromShortSyntax to correctly reflect element ('from' instead of 'form')
No issue existing for this, discussed in #2866

fix(typo): correct typo in TaskActionTypes enum

---

src/assets/i18n/de.json

Corrected wrong translation about order numbers of recurring tasks.
The translation of the description of the order number of recurring tasks was false in German. It said something like "A **lower value** means, the task is at the top of the list, a **lower number** means, the task is at the bottom of the list."
The meaning of the order number was not understandable in German.

Corrected wrong translation (recurring tasks)

---

electron/main-window.ts

Hide the app from the dock when the _Minimize to Tray_ option in _Settings > Misc_ is enabled.
closes https://github.com/johannesjo/super-productivity/issues/3393

hide app from dock when `isMinimizeToTray` is enabled

---

src/assets/i18n/zh.json
src/assets/i18n/zh_tw.json

This Pull Request introduces translations for part of the `super-productivity` JSON content into Simplified Chinese (zh) and Traditional Chinese (zh_tw).
The changes primarily include translations for various UI elements, reminders, time tracking features, and other common interface components. The translations aim to maintain consistency and clarity in line with the existing terminology used within the application.
Please review the updates and suggest any modifications if necessary. I look forward to your feedback. Thanks for the opportunity to contribute to this project!

feat(i18n): translate JSON content into Simplified and Traditional Chinese

---

src/app/features/shepherd/shepherd-steps.const.ts

Fixes a word repeat in the Shepherd guide

docs:(shepherd) Fix typo in guide text

---

src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts

The tasks used the internal ID when retrieving Gitlab issues. With this change, it uses the issue number, so that time submission works again. Tested locally with an on-premise Gitlab instance.
#3447

Fix #3447 Gitlab time submission

---

src/assets/i18n/fr.json

In french, the help provides a false indication regarding the format to use for the start time of a repeated task : the help indicates "15h00", but the fact is that the correct format is "15:00".

Fix time format in start time description for repeated task in french

---

Dockerfile
README.md
docker-compose.yaml
nginx/default.conf.template
webdav.yaml

I saw @johannesjo mentioned in a [comment](https://github.com/johannesjo/super-productivity/issues/3513#issuecomment-2375125846) that he is interested in bundling a webdav server to the super-productivity docker container. So... I made a prototype of it.
This patch provides an optional way to integrate an external WebDAV server so that the super-productivity container can serve as a WebDAV server with base url http://localhost/webdav/ . It includes the following changes:
**Replace the default nginx config file**
Besides serving the web app, the new nginx config file also forwards all the requests with paths starting with "/webdav/" to a backend WebDAV server specified by the environment variable WEBDAV_BACKEND. Note that during forwarding, the path prefix "/webdav" will be removed.
**Use …

feat: webdav integration

---

package-lock.json
src/app/features/tasks/short-syntax.spec.ts
src/app/features/tasks/short-syntax.ts

Hello there,
The latest version (`2.7.7`) of the `chrono-node` package contains a commit which should resolve scheduled time components being incorrectly offset when parsed:
- https://github.com/wanasit/chrono/commit/696d2479ce5295c9ad830ad6ac8cb2253130a8f9
I've introduced an extra test to cover this case for posterity. Note it'll fail if using `2.7.6` (as one would expect).
Also redacted what appears to be a superfluous `console.log` as I was investigating the issue to begin with.
#3192
Closes #3192

fix: parse scheduled times using local time zone (#3192)

---

android/app/src/main/res/values/strings.xml

The app name is now set to Super Prod on Android to avoid truncation issues.
- https://github.com/johannesjo/super-productivity/issues/3576
- [✅] New functionality includes testing.
- [✅] New functionality has been documented in the README if applicable. (No needed)

chore: change the display name of the android app to "Super Prod" #3576

---

src/app/features/tasks/short-syntax.ts

This PR removes the check for task start time  < current time in the `parseScheduleDate` function.
With this condition, if an user schedules a task with a time less than current time, the day of the task will be set to the next day.
```
} else if (start.date().getTime() < now.getTime()) {
plannedAt = start.date().setDate(start.date().getDate() + 1);
}
```
There are two holes with this logic:
- For example, the current time is 2024-10-17T14:37. If a user schedules the task as 2024-10-18T13:37, the date will be parsed as 2024-10-19T13:37 since 13:37 < 14:37
- There is a test in `short-syntax.spec.ts` that uses this condition. The tested time is 13:37. It will fail if anyone runs the test after 13:37.
```
it('should parse scheduled date using local time zone when unspecified', () => {
const …
```

remove check for startTime < currentTime

---

src/app/features/tasks/add-task-bar/add-task-bar.component.html
src/app/features/tasks/add-task-bar/add-task-bar.component.ts
src/app/features/tasks/short-syntax.spec.ts

When a user adds a task and types "+", it will display a dropdown list of currently unarchived projects.
**Caveat**: These changes caused the test [should parse scheduled date using local time zone when unspecified](https://github.com/johannesjo/super-productivity/blob/master/src/app/features/tasks/short-syntax.spec.ts#L838) to fail. I've temporarily commented out the test and will investigate it further.
Partially solves #3544

Feat: display project dropdown when typing "+"

---

src/app/features/shepherd/shepherd-steps.const.ts

Fixes 'Reminders' being highlighted instead of 'Calendars' in the onboarding tutorial.
Closes #3612.

Fix #3612: wrong index for Calendars in tutorial

---

src/app/ui/chip-list-input/chip-list-input.component.ts

Enables the users that uses cyrillic letters to add tags with the cyrillic letter `б` that was being recognized as a separator for tags. Now the user can add this character and press enter to create the tag.
[It seems to be a know issue on Angular Material as well.](https://github.com/angular/components/issues/13989)
https://github.com/johannesjo/super-productivity/issues/3640
Thanks!

Enable Cyrillic letters that was recognized as separator

---

build/linux/PKGBUILD_template

New packaging seems to change a couple of things:
1. Package version is no longer included on the filename of the release artifact
2. Looks like the directory inside the package new includes spaces on the target install dir
Closes https://github.com/johannesjo/super-productivity/issues/3656

Update Arch Linux PKGBUILD_template for new artifacts changes

---

.github/workflows/publish-to-hub-docker.yml
Dockerfile
README.md

Add support for multi-arch Docker images. Built and supported images are:
* `linux/amd64`
* `linux/arm64`
* `linux/arm/v7`
* Closes #3694
The tests have been performed using `act` to push the created images on my DockerHub repository, available [here](https://hub.docker.com/repository/docker/cristianlupascu/super-productivity/tags) to try and pull.
Checking the full `uname` of the containers yields:
* ARMv7
```
❯ docker pull --platform linux/arm/v7 cristianlupascu/super-productivity:multiarch-docker-build
❯ docker run -d --rm --platform linux/arm/v7 -p 80:80 cristianlupascu/super-productivity:multiarch-docker-build  
59965a0ee14ace8205018a96deec0c12f01cd14fe5b410c39ba632bbad850b27
❯ docker exec -it 59965a0ee14ace8205018a96deec0c12f01cd14fe5b410c39ba632bbad850b27 /bin/ash
/ # uname -a …
```

Add Multi-Architecture (ARM64) Support for Docker Image

---

android/app/src/main/java/com/superproductivity/superproductivity/webview/JavaScriptInterface.kt

- replaced `DocumentFileCompact` with `DocumentFile`
- replaced usage of absolute paths by `DocumentFile` uri
- add permanet permission request for read and write
- #3577 
I got the following push verification failure, but am sure if it is related to my changes, because I did not touch any timezone settings. 
Can you please help me on this one ?
```
❯ git push fork fork/nextcloud-local-file
husky > pre-push (node v22.9.0)
> superProductivity@10.0.11 lint
> ng lint
Linting "sp2"...
All files pass linting.
> superProductivity@10.0.11 test
> cross-env TZ='Europe/Berlin' ng test --watch=false
✔ Browser application bundle generation complete.
26 10 2024 11:09:37.771:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
26 10 2024 11:09:37.773:INFO [launcher]: Launching …
```

Android: Use DocumentFile Uri instead of Absolute Full Path

---

src/app/ui/duration/string-to-ms.pipe.spec.ts
src/app/ui/duration/string-to-ms.pipe.ts

Allow:
1. to input duration without spaces: `2h30m`
2. to use floats: `2.5h`
3. to omit last unit: `1h30`
#3736
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented in the README if applicable.

feat: improve durations input format #3736

---

docs/github-access-token-instructions.md

This was hard to find. It is under Settings, Developer Settings, etc. 
Current instruction doesn't help.
Adds link to the right settings page on Github

Add Github Access Token settings page link

---

README.md

Add install instructions for Linux users who want to use Flatpak. The Flatpak exists and is pulled from this repo, but just doesn't show up in the readme yet.

Add Flathub to README

---

electron/jira.ts
package-lock.json
src/app/features/issue/providers/jira/jira-api.service.ts
src/app/features/issue/providers/jira/jira.const.ts
src/app/features/issue/providers/jira/jira.model.ts

Introduced a new option to use Personal Access Tokens (PAT) for Jira authentication. Updated relevant configurations, models, and request headers to support this feature. This enhances security and provides an alternative to basic authentication.
#3808

Reimplemented support for Jira Personal Access Tokens (PAT)

---

docs/caldav.md
src/app/features/issue/providers/caldav/caldav-client.service.ts
src/app/features/issue/providers/caldav/caldav-issue/caldav-issue.effects.ts

Have a task that was imported from CalDAV?
Now, when you update the title/summary it'll be pushed to the CalDAV server.
This is a basic draft for the PR. Looking to hear if there's any feedback.
The codebase has quite a lot going on so I'm not sure if I'm breaking any conventions.
Look forward to hearing more!
PS: I only changed the one line of the table in the readme but the linter changed the rest. Let me know if that needs to be pulled into a separate PR.
Closes #3886
- I don't see any testing infra setup for CalDAV and I'm not so familiar with the tooling so pointers would be appreciated.

sync title (aka summary) from SP -> CalDAV server

---

src/app/features/issue/providers/gitlab/gitlab-issue/gitlab-issue.effects.ts

Fix for the gitlab dialog not opening on finished day. Removed code from https://github.com/johannesjo/super-productivity/commit/d524b8f3b36a4ba07acdcd2d60c53700b499e712#diff-f6deb54e22b334f31e4f46c15d7da12badc57ba085ce01a24f505d4dc58d5ec8 added to the constructor of `src/app/features/issue/providers/gitlab/gitlab-issue/gitlab-issue.effects.ts`.
#3902

fix: gitlab issue tracking submit dialog opening #3902

---

src/app/features/tasks/task-detail-panel/task-detail-panel.component.ts

Prevents page from changing or app from closing upon pressing the back button (in android or with a mouse). This is done by using `window.history` to keep the panel as another history state. When the panel is destroyed, the history entry is deleted. And when going back in history is attempted, the panel closes itself.
#3607

Prevent page from closing when pressing back in task detail panel

---

README.md

Hi, I would appreciate if we can include the flathub package near the top of the readme, I personally did not know the flathub package was supported until a few days ago because i did not see it listed there and didn't scroll down.
> List any existing issues this PR resolves
I was not able to find any issues regarding this.

add flathub package to top of readme

---

src/app/features/config/default-global-config.const.ts
src/app/features/config/form-cfgs/domina-mode-form.const.ts
src/app/features/config/global-config.model.ts
src/app/features/domina-mode/getAvailableVoices.ts
src/app/features/domina-mode/store/domina-mode.effects.ts
src/app/util/speak.ts

https://github.com/johannesjo/super-productivity/discussions/2991
As mentioned in Discussion, it is very nice to have the ability to choose which voices you would like to use.
This change basically just adds a list to the settings that has all the voices, it adds a voice parameter to the speak function and adds two new functions getAvailableVoices and getDefaultVoice. The first is used to populate the list and the second is to recreate the same behavior that already happens when using Domina mode. The default voice is just chosen in that case.
https://github.com/johannesjo/super-productivity/discussions/2991
If needed I can also open a separate issue for this.

Added Option to Choose Voices for Domina mode.

---

docs/add-new-integration.md

This pull request adds a comprehensive guide for creating new issue tracker integrations. Please review the changes in docs/add-new-integration.md.

docs: add comprehensive guide for creating new issue tracker integrations

---

src/app/features/tasks/task-context-menu/task-context-menu-inner/task-context-menu-inner.component.html

Fixes the wrong hint for the rescheduling button. Example of the current wrong behavior:
https://github.com/johannesjo/super-productivity/issues/4024

fix: wrong hint for reschedule button

---

src/app/features/tasks/add-task-bar/short-syntax-to-tags.ts
src/app/features/tasks/short-syntax.ts
src/app/features/tasks/store/short-syntax.effects.ts
src/app/features/tasks/task.model.ts

With this PR, when a user schedules a task with short syntax but doesn't give a specific time, the task will simply be planned for the day, without any time attached.
Under the hood, scheduled tasks without a specific time will dispatch [`planTaskForDay`](https://github.com/johannesjo/super-productivity/blob/master/src/app/features/planner/store/planner.actions.ts) action. This is in contrast to scheduled tasks with a specific time which will trigger [`scheduleTask`](https://github.com/johannesjo/super-productivity/blob/master/src/app/features/tasks/store/task.actions.ts) action.
Visually, the task scheduled without time will be located at the top, underneath the relevant day column in the Planner view.
List any existing issues this PR resolves: #4049

feat: handle tasks scheduled without a specific time

---

.github/workflows/build-android.yml
README.md

improves the pipeline responsible for building and releasing a apk release for github actions 
- adds the obtanium badge
- fixes the build-android pipeline and change the run triggers
- adds the dependency for [android-actions/setup-android@v3](https://github.com/android-actions/setup-android)
IMPORTANT: this forces the CI to accept the android sdk license in order to work - this has been highlighted in the action file and the most verbose version for the license acceptance has beed selected for transparency 
resolves #3596

Add apk releases for github

---

src/app/features/tasks/short-syntax.spec.ts
src/app/features/tasks/short-syntax.ts

#4083
Fix issue where tags were not removed from the task title correctly.
This PR fixes an issue where tags were not properly removed from the task title when they were already assigned to the task. Previously, tasks that had tags both in the title (`#tag`) and in the `tagIds` field were not processed correctly, leading to incorrect title formatting.
- Previously, only newly added tags were removed from the title. The logic in short-syntax.ts has been updated to ensure all existing tags in the title are removed correctly. Now, if a task is created with a tag matching the current view, it will be automatically removed from the title.
- Added unit tests in `short-syntax.spec.ts` to confirm the fix.

Fix #4083 (tasks): resolve tag removal issue

---

e2e/commands/addTaskWithRepeatedTags.ts
e2e/n-browser-interface.ts
e2e/src/short-syntax.e2e.ts
src/app/features/tasks/add-task-bar/short-syntax-to-tags.ts
src/app/features/tasks/store/short-syntax.effects.ts

When you create a task you can use the pound sign to assign it tags, and if the tag dosent exist it creates it.
There was an error in the parsing of the user input that allowed the user can create multiple tags with the same name, which was not what was intended
I changed two short syntax files so that on display repeated new tags are not shown, and when trying to create it makes sure it dosent create duplicares.
Trying to create a new task with multiple new tag of the same name will no longer work, resulting the in creation of a single tag with that name, with the fact being visually clear to the user
- [Y ] New functionality includes testing.
- [N ] New functionality has been documented in the README if applicable. (non applicable)

Fix #4046: Mulitple Same Name Tags being created.

---

src/app/features/tasks/short-syntax.spec.ts
src/app/features/tasks/short-syntax.ts
src/app/ui/duration/string-to-ms.pipe.ts

Fixed the issue #4184 where you could not insert 1.5h or any decimal value when inputing time stamp in the quick add method of creating a task. To test execute project with instructions given in the repository and add a new task (shift+A) and write the title of a new task such as "task 1.5h" or "task 1.5h/3.5h". Also added test cases for this fix.
- [✅] New functionality includes testing.
- [❌] New functionality has been documented in the README if applicable.

Fix #4184: Added fractional time parsing when creating a new task

---

src/app/core/data-repair/data-repair.util.ts

Fix v0 -> v2 migration where monday-sunday expects boolean but gets undefined
- #4272
Tested a bit - don't think it'll break anything. Realized that just setting it to true will cause unintended behavior when problems aren't here, so using ?? operator whatever its called in typescript to just reuse value if it exists, only set to true if it's missing

fix: Import fails when weekdays not defined

---

src/app/features/tasks/short-syntax.spec.ts
src/app/features/tasks/short-syntax.ts
src/app/util/month-time-conversion.ts

When user creates a new task which includes short syntax for date, then following by a two-digit number, the number will be interpreted as year.
For example: **"Task `@`14/4 90m"**. Implication: User schedules the task for 14/4 going forward and estimates the task as taking 90 minutes. Two problems:
- This task will be scheduled for 14/4/1990 because Chrono understands 90 as 1990.
- The task title will include the word "m" when it should have been escaped.
Changes I've made:
- Write a custom parser that checks if the task title contains string in the format of `DD/MM YY`. The regex pattern is more complicated than that, because there are so many ways a user can write date informally. It doesn't take into account syntax like "August 8 90m".
- The parser will set the year for the task to …

Fix Date Parser Any Parsing Two-Digit Number as Year

---

electron/backup.ts
electron/ipc-handler.ts

If we are running from the Windows store, we return a modified version of BACKUP_DIR to getBackupPath which is only called for the UI in settings. We cannot change BACKUP_DIR itself as it is used for the actual backup calls. 
The logging in backup.ts was not changed. The extra const was probably not necessary but I felt it was cleaner and is available if you want to correct the logging as well.
I have never coded in JS, Node, or Electron, have no way to test this code (tested the CONST.replace syntax on w3schools). Despite Microsoft mentioning Roaming going away in Windows 11, I did an install on Windows 11 and verified that it matched Windows 10.
3h20m and it's complaining about me not taking a break.
https://github.com/johannesjo/super-productivity/issues/995

Fix 995 define BACKUP_DIR_WINSTORE and return it for getBackupPath

---

src/_variables.scss

When following the tutorial, users are prompted to delete a task by right-clicking it. However, the task context menu was being obscured by the tutorial dialogue, making it impossible to access the delete option
The issue was resolved by adjusting the z-index of the tutorial dialogue, ensuring that the task context menu always appears on top when right-clicking a task during the tutorial.
The task context menu is no longer obscured by the tutorial dialogue.
Users can now properly interact with the menu options and delete tasks while following the tutorial.

Fix #4034: Task context menu hidden by tutorial dialogue

---

src/app/pfapi/api/sync/sync.service.ts

I looked a bit further into https://github.com/johannesjo/super-productivity/issues/4433 and I _think_ the bug was introduced by wrongful bracketing in https://github.com/johannesjo/super-productivity/commit/d1a77c9ac3a697d1606adc05dd26f225b646ffa6.
The behavior I'm observing is that the initial sync correctly uses the meta sync service, but after selecting 'Keep remote', it wrongfully uses the model sync services and tries to download files other than `_meta_` that were never uploaded, even though the sync provider has `isLimitedToSingleFileSync` set to `true`. However, I'll admit that I don't understand the code 100% so this assumption should be double-checked. :sweat_smile:

Fix keeping remote data for local file sync

---

Dockerfile
docker-entrypoint.sh

Our custom `docker-entrypoint.sh` starts nginx by directly calling `nginx -g "daemon off;"`. However, we need the `docker-entrypoint.sh` built-in in the nginx docker image to convert `default.conf.template` to the actual nginx config file. Without going through nginx's `docker-entrypoint.sh`, the resultant docker image fallback to the default nginx configuration, which doesn't forward traffic to webdav backend server.
This patch fixes this by calling the nginx's `docker-entrypoint.sh` at the end of our custom `docker-entrypoint.sh`.
The first issue in https://github.com/johannesjo/super-productivity/issues/4545#issuecomment-2974843258

fix: start nginx via its built-in entrypoint script

---

src/app/imex/sync/sync-config.service.ts

The spread operator `...` replaces `baseConfig.webDav` with `defaultOverride.webDav` entirely, instead of merging them. Hence, the default sync folder path in `baseConfig.webDav` is wiped out.
This patch fixes this issue by manually providing a merged `webDav`.
The second issue in https://github.com/johannesjo/super-productivity/issues/4545#issuecomment-2974843258

fix: preserve default sync folder path when no overriding

---

Dockerfile

This patch reorders some commands in `Dockerfile` to save time on building the docker image.
The main goal is to only copy `package.json` and `package-lock.json` into the docker environment before installing dependencies via npm. Therefore, if the dependencies do not change (but other files may change), `docker build` will automatically use cached layers in previous build, instead of re-downloading the same set of dependencies again. This could save build time, especially during development at local machine.
Furthermore, use `npm ci` instead of `npm i` can speed up the build process in CI environment.
However, I notice that `package.json` and `package-lock.json` are out of sync now. So, `npm i` remains in `Dockerfile` as fallback for now. Once the two json files are in sync, this fallback …

refactor: Dockerfile only copy package*.json before installing dependencies

---

src/app/util/adjust-to-live-formly-form.ts

Fix for ModelValidationError: ModelValidationError #4654
After pressing Enter to confirm the provided value, the input is treated as a string, whereas a number is expected. This causes a validation error to occur.

fix: fix for ModelValidationError: ModelValidationError #4654

---

electron/plugin-node-executor.ts

Enable plugins to access the Node.js 'os' module for system information gathering alongside the existing fs and path modules.
Changes:
- Updated canExecuteDirectly() regex pattern to allow 'os' module imports
- Added os module import to executeDirectly() sandbox environment
- Extended sandbox require() function to provide access to os module
This allows plugins to access system information like platform, architecture, memory usage, CPU info, and network interfaces through the standard Node.js os module while maintaining the existing security restrictions.
The os module is considered safe as it provides read-only system information and doesn't allow file system modifications or process execution.
Fixes #4849

feat: add os module support to plugin node executor

---

src/app/features/issue/providers/caldav/caldav-cfg-form.const.ts

Currently, the pattern to validate the base URL for a CalDAV instance needs to contain a domain, like `example.com`. The only exception is the fixed hostname `localhost`. As it is also possible to host a CalDAV server like Nextcloud using another local hostname without a domain, the pattern should also accept these.
For example, my Nextcloud instance is available using `https://local/nextcloud`.
This PR changed the URL Regex to `/^(http(s)?:\/\/)?([\w\-]+(?:\.[\w\-]+)*)(:\d+)?(\/\S*)?$/i`, to support both domains and simple hostnames in validation.
As a question, I only found about Super Productivity today and I am already in love with it. Are you open for constributions to the issues providers? I would like to improve the sync and add some providers. Also two-way sync like partially …

Allow simple hostnames in CalDAV URL

---

src/app/features/simple-counter/simple-counter-button/simple-counter-button.component.scss

I just removed the transform on the material icons 
[#4924](https://github.com/johannesjo/super-productivity/issues/4924)

Fix: center material icon #4924

---

src/app/features/tag/tag-list/tag-list.component.ts

This orders the tags in alphabetical order based on their title. This is applied to all regular tags but the optional project tag (when enabled) will always appear first on the list.
Fix #4871 
Fix #4111

Fix #4871 - Sort tag list in alphabetical order

---

src/app/pfapi/api/sync/providers/local-file-sync/local-file-sync-android.ts
src/app/pfapi/api/sync/providers/local-file-sync/local-file-sync-electron.ts
src/app/pfapi/api/sync/sync-provider-private-cfg-store.ts

On Android and the Electron app, it is not possible to use the local file sync as of the latest version, since you can't select the sync directory unless you already have a config generated. This PR fixes this by using an upsert function for the directory selection.
fixes #4938

fix: solve local file sync directory path not being selectable

---

src/app/core/confetti/confetti.model.ts
src/app/core/confetti/confetti.service.ts
src/app/features/focus-mode/focus-mode-task-done/focus-mode-task-done.component.ts
src/app/features/simple-counter/store/simple-counter.effects.ts
src/app/pages/daily-summary/daily-summary.component.ts

This PR fixes an issue where the "Disable All Animations" setting was ignored by confetti animations. It also adds typing for the canvas-confetti package.
https://github.com/johannesjo/super-productivity/issues/4736

Fix #4736: confetti celebration does not respect the "Disable All Animations" anymore

---

electron/electronAPI.d.ts
electron/ipc-handler.ts
src/app/features/tasks/store/task-electron.effects.ts

This PR implements handling progressBarMode none in the electron API and uses that to remove the progressbar when a task with one is marked as done.
Fixes #3701

Fix: Remove progressbar on task completion in electron

---

src/app/pages/search-page/search-page.component.ts

[RecordRTC-2025724-hz8bopdrjla.webm](https://github.com/user-attachments/assets/281e24de-19d5-4d3c-9f5b-9fe56e5f3be1)
The search functionality was incorrectly converting task titles and notes to lowercase during data preparation, causing search results to display with incorrect capitalization.
Data Preparation (lines 95-96): Removed .toLowerCase() calls when storing task title and notes in the searchable items array
Search Filtering (lines 153-154): Added .toLowerCase() calls during the actual search comparison to maintain case-insensitive search while preserving original text formatting
`Result`: Search results now display with proper capitalization while maintaining case-insensitive search functionality.
This change fixes the search results capitalization issue in …

fix: search results have incorrect capitalization

---

src/app/features/issue/providers/jira/jira-cfg-form.const.ts

I was looking for a way to allow super-productivity to connect to jira through a corporate proxy and realized the code already had support for it, but the UI config option was disabled.   All I'm doing is uncommenting it to let it show up in the ui again.
Note: The commit commenting the option out mentioned it being being an edge case, but I think a lot of corporate/enterprise users would run into the same issue due to corporate proxies mitm'ing everything and/or using a self-signed CA.   It also didn't look like there's a built-in way for electron apps to use the system trust store.
- https://github.com/johannesjo/super-productivity/issues/348

Re-enable the UI option to allow self-signed certs for Jira

---

src/app/features/boards/boards.component.html
src/app/features/boards/boards.component.ts

- Create `MatMenu` for each tab. The menu trigger is in an empty `<span>` element.
- Attach click event handlers to each tab. It will open the menu if the **clicked tab is the active tab**. Logic for checking it is a bit hacky because tab index update happens before the click event finishes propagation. Idea comes from [here](https://stackoverflow.com/a/50574107/12160227)
- Dispatch the action for creating a new board, passing the same `cols` and `panels parameters as the selected board. The `id` is created on the spot. The `title` parameter is as `${selectedBoard} (copy)`.
**Feature preview**
https://github.com/user-attachments/assets/5bb42028-ec22-4f6a-b331-7464ce91fbac
The newly duplicated board has a different title from the original board because that's how the latter's title was …

Feat #4098: Add duplicate function to boards

---

src/app/ui/better-drawer/better-drawer-container/better-drawer-container.component.scss
src/app/ui/better-drawer/better-drawer-container/better-drawer-container.component.ts
src/app/util/styles.ts

This PR solves an issue where the right sidebar of better-drawer-container would unnecessarily expand when dragging elements to the right side, causing the entire layout to shift to the side and making the panel visible (even though isOpen: false)
A small refactoring was also done to make the code cleaner:
1. Unnecessary and old commented css properties were removed
2. Helper types `StyleObject` and `CssString` were created, as well as a function for converting `StyleObject` to a `CssString`
https://github.com/johannesjo/super-productivity/issues/5017

fix: incorrect sidebar opening when dragging

---

tools/add-missing-i18n-variables.js

This pull request introduces a new script, `add-missing-i18n-variables.js`, to automate the process of synchronizing translation files with the English reference (`en.json`). The script ensures all language files in `src/assets/i18n` have the same keys as `en.json`, filling in missing keys while preserving existing translations and key order.
Key addition:
**Internationalization tooling:**
* Added `tools/add-missing-i18n-variables.js`, a script that updates all language JSON files in `src/assets/i18n` by merging missing keys from `en.json`, preserving key order and existing translations, and providing a summary of updates and errors.

feat: add script to update missing i18n keys from en.json

---

electron/main-window.ts

A friend of mine had a similar issue with outlook.live.com calender links, since he is not using a business account.
Appearently outlook.live.com needs the User-Agent to be set in http requests since a few weeks.
Not sending it broke Outlook Live calendar integration
https://github.com/johannesjo/super-productivity/issues/4677

added User-Agent Header to outlook.live.com requests

---

electron/main-window.ts
electron/tsconfig.electron.json
package-lock.json
package.json
src/app/core-ui/side-nav/side-nav-item/side-nav-item.component.html
src/app/core-ui/side-nav/side-nav-item/side-nav-item.component.scss
src/app/core-ui/side-nav/side-nav-item/side-nav-item.component.ts
src/app/features/config/icon-input/icon-input.component.html
src/app/features/config/icon-input/icon-input.component.ts
src/app/features/simple-counter/simple-counter-button/simple-counter-button.component.scss
src/app/features/tag/tag/tag.component.html
src/app/features/tag/tag/tag.component.scss
src/app/features/tag/tag/tag.component.ts
src/app/features/tasks/add-task-bar/add-task-bar-actions/add-task-bar-actions.component.html
src/app/features/tasks/add-task-bar/add-task-bar-actions/add-task-bar-actions.component.scss
src/app/features/tasks/add-task-bar/add-task-bar-actions/add-task-bar-actions.component.ts
src/app/util/extract-first-emoji.spec.ts
src/app/util/extract-first-emoji.ts
src/app/util/is-emoji.ts
tools/lighthouse/budget.json

Fixes: #4587 
This PR fixes an issue where users could add multiple UTF-8 emojis as project icons, causing visual overlap with the project name. The fix ensures that only a single emoji can be used as a project icon at any time.
Solution: Showing the single emoji replacement behavior
https://github.com/user-attachments/assets/06a9b9fd-18b2-45e7-83eb-d304e9225d1d
- Enhanced emoji validation logic to ensure only single emojis are accepted
- Improved paste handling to extract and use only the first emoji from pasted content
- Added utility functions for robust emoji detection and validation
- Updated input behavior to replace existing emoji when a new one is entered, preventing accumulation

fix: ensure single emoji icons render correctly 

---

src/app/features/tasks/short-syntax.spec.ts
src/app/features/tasks/short-syntax.ts

Hello there,
I've revised the regular expression that was being used to parse project names from task text input for better accuracy. When adding new tasks, it should better cope with project names which happen to use special characters part of the short syntax feature.
The following screen capture is behaviour based on `15.0.3` via https://app.super-productivity.com.
And here's the behaviour based on the current state of `master` plus my changes.
I've included a whole slew of data-driven tests to try capture as many parse cases as possible. If this is too much, let me know and I can redact as necessary.
#4225

fix(task): improve project name parsing from task input (#4225)
