johannesjo/super-productivity

- app-src/scripts/agenda-and-history/daily-agenda/daily-agenda-d.html
- app-src/scripts/daily-planner/daily-planner-d.html
- app-src/scripts/daily-summary/daily-summary-d.html
- app-src/scripts/dialogs/add-task/add-task-c.html
- app-src/scripts/dialogs/distractions/distractions-c.html
- app-src/scripts/dialogs/help/help-daily-planner.html
- app-src/scripts/dialogs/help/help-daily-summary.html
- app-src/scripts/dialogs/help/help-global-link-list.html
- app-src/scripts/dialogs/help/help-settings.html
- app-src/scripts/dialogs/help/help-task-list.html
- app-src/scripts/dialogs/help/help-time-tracking-history.html
- app-src/scripts/dialogs/jira-add-worklog/jira-add-worklog-c.html
- app-src/scripts/dialogs/jira-set-status/jira-set-status-c.html
- app-src/scripts/dialogs/notes/notes-c.js
- app-src/scripts/dialogs/simple-task-summary/simple-task-summary-c.html
- app-src/scripts/dialogs/was-idle/was-idle-c.html
- app-src/scripts/dialogs/welcome/welcome-c.html
- app-src/scripts/hint/hint-d.html
- app-src/scripts/main-header/main-header-d.html
- app-src/scripts/settings/backup-settings/backup-settings-d.html
- app-src/scripts/settings/git-settings/git-settings-d.html
- app-src/scripts/settings/jira-settings/jira-settings-d.html
- app-src/scripts/settings/keyboard-settings/keyboard-settings-d.html
- app-src/scripts/settings/project-settings/project-settings-d.html
- app-src/scripts/work-view/work-view-d.html
Most of this is fixing grammar and typos, although some of it might be opinion based (I'm not the best with it myself).
> style: reword, fix and improve various text

- app-src/scripts/dialogs/pomodoro-break/pomodoro-break-c.html
Hi, just found a little typo and thought I'd save you some time.
By the way, thanks for this awesome tool, use it everyday.
> style: fix little typo

- src/app/features/project/project.const.ts
- src/app/features/project/project.model.ts
- src/app/features/worklog/worklog-export/worklog-export.component.html
- src/app/features/worklog/worklog-export/worklog-export.component.ts
Reverts johannesjo/super-productivity#164
> Revert "feature: export grouby option"

- src/app/features/project/project.const.ts
- src/app/features/project/project.model.ts
- src/app/features/worklog/worklog-export/worklog-export.component.html
- src/app/features/worklog/worklog-export/worklog-export.component.ts
Sorry for the trouble. This should fix it.
> Fixes issues with #164

- src/assets/i18n/es.json
Improved some strings to be more clear in the UI
Hello from dev.to help request :)
> feat(i18n): improve spanish translations

- src/assets/i18n/fr.json
Improved some translations that were not suited to the context.
> feat: improve french translation

- src/assets/i18n/fr.json
Hi,
I know there isn't any issue about it at the moment, but the french translation of the app was terrible. (I'm guessing Google Translate?)
I took time to fix it :)
Keep up the great work!
> Improve french translation

- src/assets/i18n/es.json
Hi,
In this PR I'm reviewing the spanish translation, related to this issue #243
> Improve spanish translation

- src/assets/i18n/fr.json
> Docs: #243 Improve french translations

- src/app/features/project/migrate-projects-state.util.ts
- src/app/features/tasks/migrate-task-state.util.ts
- src/app/util/numeric-converter.ts
This is what I did until now.
I will try to fix the other problems as well.
> fix: fix date migration error

- src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
This should solve the error in #317.
> fix: filter error for projects with no issues

- src/assets/i18n/zh.json
Give a more precise translation for word "host"
> Update translation in Chinese

- src/assets/i18n/pt.json
Improved the portuguese translation, there was some mistakes about accents, non-translated words, etc
> Improve portuguese translation

- src/app/features/config/select-project/select-project.component.html
> fix: text overlap

- electron/indicator.ts
Change the tray icon according to the windows theme.
#554
> feat: change tray icon theme 

- src/assets/i18n/ja.json
Improve japanese translation.
None
> i18n: improve japanese translation

- src/app/features/config/form-cfgs/sound-form.const.ts
Play task done sound when selected on settings.
Resolve [this comment](https://github.com/johannesjo/super-productivity/issues/180#issuecomment-707980697) in #180
> feat: play done sound when selected on settings

- src/app/pages/project-overview-page/project-overview-page.component.scss
Missing space between "Create new" and "Import from file" under "Create Project" section
> Missing space between buttons

- src/assets/i18n/de.json
I noticed and fixed a few small spelling mistakes or missing spaces and changed weird translations or added missing translations to german.
This is my first pull request to open source, so be patient please! 😱 😄 
Nothing here...
> fix(i18n_de): fix some typos and translation flaws and added some missing translations to german

- .eslintrc.json
- src/app/imex/sync/google/google-drive-sync.service.ts
Re-enable no-shadow rule with ESLint and fix subsequent errors.
> feat(eslint): fix no-shadow rule

- .eslintrc.json
- src/app/core/error-handler/global-error-handler.util.ts
- src/app/core/migration/migration.service.ts
- src/app/features/config/config-form/config-form.component.ts
- src/app/features/issue/providers/github/github-api.service.ts
- src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts
- src/app/features/issue/providers/jira/jira-api-responses.d.ts
- src/app/features/issue/providers/jira/jira-api.service.ts
- src/app/features/reminder/reminder.model.ts
- src/app/features/worklog/worklog-week/worklog-week.component.ts
- src/app/imex/sync/dropbox/dropbox-api.service.ts
- src/app/imex/sync/google/google-api.service.ts
- src/hammer-config.class.ts
Enable ban-types rule after migrating from TSLint to ESLint
> feat(eslint): enable ban-types eslint rule

- .eslintrc.json
- src/app/features/work-context/work-context.util.ts
- src/app/util/numeric-converter.ts
Re-enable prefer-const rule and fix subsequent errors
> feat(eslint): re-enable prefer-const rule and fix subsequent errors

- .eslintrc.json
- src/app/features/metric/metric.model.ts
- src/app/features/metric/obstruction/obstruction.model.ts
- src/app/features/note/store/note.reducer.ts
- src/app/imex/sync/sync.model.ts
Re-enable no-empty-interface rule and fix errors.
> feat(eslint): re-enable no-empty-interface rule and fix errors

- .eslintrc.json
- src/app/features/tasks/task/task.component.ts
- src/app/features/work-view/work-view.component.ts
- src/app/ui/better-drawer/better-drawer-container/better-drawer-container.component.ts
Re-enabled no-unused-expressions rule.
> feat(eslint): re-enabled no-unused-expressions rule and fixed errors

- .eslintrc.json
- src/app/core/persistence/persistence.service.ts
- src/app/features/issue/issue.service.ts
- src/app/features/project/dialogs/create-project/dialog-create-project.component.ts
- src/app/features/project/store/project.effects.ts
- src/app/features/tasks/add-task-bar/add-task-bar.component.ts
- src/app/features/tasks/task.service.ts
- src/app/features/work-context/work-context.util.ts
- src/app/features/worklog/worklog.service.ts
- src/app/imex/sync/google/google.const.ts
- src/app/ui/formly-translate-extension/formly-translate-extension.ts
re-enable max-length ESLint rule and fix errors. Related to #803.
> feat(eslint): re-enable max-length rule and fix errors

- src/app/pages/schedule-page/schedule-page.component.html
> Scheduled tasks view: change time format for due time to hh to allow for proper 24h display

- .eslintrc.json
- src/app/features/issue/providers/github/github-api-responses.d.ts
- src/app/features/issue/providers/github/github-issue/github-issue-map.util.ts
- src/app/features/issue/providers/github/github-issue/github-issue.model.ts
- src/app/features/issue/providers/gitlab/gitlab-issue/gitlab-issue-map.util.ts
- src/app/features/issue/providers/gitlab/gitlab-issue/gitlab-issue.model.ts
Re-enable id-blacklist rule. Related to #803.
> feat(eslint): enable id-blacklist rule and fix errors

- README.md
I think this helpful enough to be added here, as prioritizing is always an implicit use case for to-do and time tracking apps
> Link to article on 'eat the frog' in SP

- src/app/features/worklog/worklog-export/worklog-export.component.ts
- src/app/features/worklog/worklog-export/worklog-export.util.spec.ts
- src/app/features/worklog/worklog-export/worklog-export.util.ts
createRows() from worklog-export has been extracted to a new file and initial tests have been implemented.
Note: I amended the suggested changes for start/endTimes initialization.
> Tests for worklog-export

- src/app/features/worklog/worklog-export/worklog-export.component.ts
- src/app/features/worklog/worklog-export/worklog-export.model.ts
- src/app/features/worklog/worklog-export/worklog-export.util.spec.ts
- src/app/features/worklog/worklog-export/worklog-export.util.ts
Hey, sorry, had to make a new PR.
So, this changes a lot and I'd understand if you wanted this to happen on a new branch.
However I can tell you that I did quite a lot of manual tests taking screenshots and it made no changes in my test scenario.
Apart from one difference on tags while grouping by worklog which was a bug before and is now fixed by refactoring. 
I think it pays out to go commit by commit as changes are clearer that way.
> Refactor worklog-export, test and documentation

- src/assets/i18n/it.json
Fixed some translation errors and translated some strings
Nothing
> Italian Translations

- .gitpod.yml
basic config to speed up gitpod launching
> add gitpod config

- src/assets/i18n/en.json
- src/assets/i18n/zh.json
Refine the Chinese(simplified) translation for Super-productivity.
As discussed before in https://github.com/johannesjo/super-productivity/discussions/1370, some Chinese terms seem not reasonable for the users. 
In this PR, I roughly proofread the translation to make it more suitable for Chinese users. 
Please refer https://github.com/johannesjo/super-productivity/discussions/1370
> Refine the translation of Chinese(simplified).

- src/app/imex/file-imex/file-imex.component.html
FIX #1423Settings page export/import CSS bug fix
**Before** 
**After**
> FIX: Settings page export/import CSS bug fix

- src/assets/i18n/zh.json
Changed some weird Chinese translations.
Some explanations:
| Key                    | original text | correted text | reason                                                       |
| ---------------------- | ------------- | ------------- | ------------------------------------------------------------ |
| PROJECT_ID             | 专案编号      | 项目编号      | "project" should be translated to "项目" for most cases.     |
| UNDO                   | 解开          | 撤销          | "解开" means "untie" rather than "undo". Here "撤销" should be used. |
| VOLUME                 | 体积          | 声量          | "体积" means the amount of space a object takes, while "音量" measures how loud a sound is. |
| ROUND_TIME_SPENT       |               |               | these two changes: noun -> verb …
> changed some weird translation in Chinese

- src/assets/i18n/pl.json
Hello, I have added translation to polish. I will update this :)
Added pl translations
-
> Created pl.json

- .github/workflows/welcome-first-time-contributors.yml
Added github action for first time contributors in the repo
#1630
> Added github action

- src/app/features/issue/providers/jira/jira-api.service.ts
> Improved the instructions to enter the wonky cookie.

- src/assets/i18n/hr.json
The translation is not complete, but it would be great, if you could release a new/nightly version, so I could check the Croatian translation in real life (on my MacOS) and make possibly necessary corrections/adjustments.
> Add Croatian translation

- src/assets/i18n/hr.json
- some updated strings
- some corrections
- translation of newly added original strings
Translation is still not complete. Untranslated:
- lines 340 - 347
- lines 536 - 538
- lines 872 - 875
- line 1076
- line 1151
> Update Croatian translation

- src/app/app.component.ts
- src/assets/i18n/en.json
> fix: remove firefox incompatible popup $firefox

- README.md
It just adds a collapsible section to the README that summarizes keyboard-shortcuts and the existing markups for task-creation.
> add info on shortcuts and markups to README

- README.md
As a new user it's been helpful to see some of these quick shortcuts and syntax in the README. One small addition to bring the project syntax up to the surface.
> Add project markup to README

- src/assets/i18n/hr.json
- some more corrections ... sorry!
> Updated Croatian

- src/assets/i18n/sk.json
> Added sk.json

- src/app/features/android/android-interface.ts
- src/app/imex/sync/web-dav/web-dav-api.service.ts
- src/app/imex/sync/web-dav/web-dav-sync.service.ts
- src/assets/i18n/en.json
See https://github.com/johannesjo/super-productivity-android/pull/17 for the relevant API.
This is needed to fix CORS in WebDAV sync in the Android app
https://github.com/johannesjo/super-productivity/issues/1847
I haven't tested this on the stable version of the Android app but in theory it should work.
> Fix CORS on Android for WebDAV

- src/assets/i18n/hr.json
Updated Croatian translation
I'd like to **reiterate my suggestion** to you use (if possible) a translation platform for translations like [Weblate](https://weblate.org/). I'm aware of the fact that this implicates some more work on your side, but IMO, it helps translators …
I found several changes/new strings in the `en.json`. I found them just by chance, as I was reviewing the english and croatian `.json` files side by side with BBEdit.
> Updated Croatian translation

- src/app/pages/project-settings-page/project-settings-page.component.ts
Fix a problem with empty project configuration after gitea integration addition
#2066
> fix: problem with empty project configuration with number #2066

- README.md
Hi @Sharik_devs,
I have created this Pull Request because I have resolved this [request for a Chocolatey package](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1293) and now, we can install **super-productivity** using [Chocolatey](https://community.chocolatey.org/packages/super-productivity).
For now, only the latest version (`7.11.5`) is available on Chocolatey. When new versions will be released, they will, then, be added to the Chocolatey package for users to enjoy. :slightly_smiling_face: 
List any existing issues this PR resolves:
>  Adds the Chocolatey package as a way to install Super Productivity

- src/assets/i18n/zh.json
‘订购’ means purchase, not order of tasks
update chinese translation
> fix(i18n): update chinese translation

- src/assets/i18n/es.json
I fixed some of the spanish translations.
> fix(i18n): update spanish translations

- README.md
Updating the README to be a little clearer, especially where the [User Data Foler](https://github.com/johannesjo/super-productivity#user-data-folder) is concerned
> update to the README for a little bit better readability

- README.md
Some spelling mistakes correction and readability improved.
> corrected some typo

- src/styles/components/_overwrite-material.scss
- src/styles/util.scss
This PR will improve button alignment in Jira setup form. Below is a screenshot of the form in my local. 
This is address [issue 2301](https://github.com/johannesjo/super-productivity/issues/2301)
> Issue 2301

- src/assets/i18n/pl.json
Update the Polish translations in the GitLab section
> fix: Update Polish GitLab translations

- src/assets/i18n/pl.json
Update the Polish translations in the GitHub section
> fix: Update Polish translations

- src/assets/i18n/tr.json
> Update Turkish translation

- src/app/features/timeline/ical/get-relevant-events-from-ical.ts
ICS format allows for timestamps to be in different timezone. This is particularly useful in defining recurring events in a daylight saving timezone. ical.js's default behaviour doesn't utilise timezone definitions included in the ICS string. This PR uses the workaround mentioned here: https://github.com/kewisch/ical.js/issues/455#issuecomment-706984325
> Correctly handle timezones in ical

- README.md
> README.md: add F-Droid badges

- src/assets/i18n/en.json
Use less confusing terminology when there is a sync conflict
> use less confusing terminology

- src/app/imex/sync/web-dav/web-dav-api.service.ts
Fix compatibility with web client
List any existing issues this PR resolves #2548
> fix compatibility with web client

- src/app/pages/config-page/config-page.component.scss
This change resolves issue #2581 by expanding the box where week days are shown.
Issue #2581 
Signed-of-by: Victor Fernando victorfernando.sis@gmail.com
> Makes all week days visible #2581

- src/assets/i18n/en.json
I've added an example for adding due date through smart date syntax.
N/A
> Add example for smart date shortcut

- src/assets/i18n/zh.json
Correct some mistakes in Chinese translation
Nothing
> Chinese translation mistakes

- README.md
Since https://github.com/johannesjo/super-productivity/pull/2041 merged, I think more people could know that super-productivity supports Gitea.
> Mention Gitea support on README.md

- src/app/features/issue/providers/github/github-api.service.ts
Fixes broken suggestions for GitHub issues.
#2749
> fix: Replace encodeURIComponent with encodeURI #2749

- src/assets/i18n/pt.json
Translating only what is necessary from the application so far, I use en.json as the basis for this.
none
- none
> Translating from en.json to pt.json. Not everything but the necessary

- CONTRIBUTING.md
- README.md
This pull request addresses and corrects grammatical and spelling errors throughout the codebase to improve code readability.
The changes include fixing typos, punctuation, and ensuring proper sentence structure without introducing functional modifications.
These updates are intended to enhance the quality of documentation and code comments.
The focus is on making the codebase more polished and user-friendly by eliminating language-related issues.
> Fix typo and Grammatical error

- src/assets/i18n/fr.json
Translation & add - Focus Mode in french
Cohesion change with github and gitlab
> Translation & add - Gitea in french

- electron/backup.ts
- electron/main.ts
- src/app/features/config/form-cfgs/automatic-backups-form.const.ts
> fix: windows backup path #2869

- src/assets/i18n/cz.json
Sry I have not enought dev skills.
> Create cz.json - experimental Czech language

- src/assets/i18n/de.json
Slight overhaul of the German language file. Correction of spelling or grammar mistakes, mistranslations and inconstistent use of the courtesy form.
None
> Overhaul of German language file "de.json"

- src/assets/i18n/tr.json
Please review the changes and merge if everything looks good.
> Update Turkish translations

- README.md
I added a section describing what Fink does and linked a guide explaining how to contribute via the Fink Localization Editor.
Requested in https://github.com/johannesjo/super-productivity/pull/3032 ([comment](https://github.com/johannesjo/super-productivity/pull/3032#issuecomment-1948066870))
> docs: update translation section 

- src/assets/i18n/zh.json
Added some Chinese translations
> feat(i18n): update Chinese translation

- src/assets/i18n/de.json
Should fix https://github.com/johannesjo/super-productivity/issues/3147
Fixes broken replacement strings in German localisation.
- https://github.com/johannesjo/super-productivity/issues/3147
> Fix broken squiggle brackets in de.json

- src/assets/i18n/zh.json
- Added some missing translations.
- Modified a translation that was slightly too long.
- Corrected an incorrect translation.
Preview the messages on https://inlang.com/github.com/ZaphireLiu/super-productivity
> Update translations for zh

- src/assets/i18n/ko.json
- fix some word spacings
- match some words accordings to context
> Update translations for Korean

- src/app/features/shepherd/shepherd-steps.const.ts
Fix grammar: "privacy very serious." ->  "privacy very seriously."
> Fix grammar in shepherd-steps.const.ts

- .github/workflows/build-publish-to-aur-on-release.yml
Handle any kind of versioning
Closes https://github.com/johannesjo/super-productivity/issues/3380
> cicd: Handle any kind of version for AUR

- src/assets/i18n/en.json
correction of translation string from e_min
closes #3391
> fix translation for min condition

- src/assets/i18n/en.json
> chore: update en.json

- src/app/imex/sync/web-dav/web-dav-api.service.ts
Fix WebDAV URL concatenation on Android
fixes #3432
> Fix WebDAV URL concatenation on Android

- src/assets/i18n/ja.json
Added some Japanese translations.
> Update translations for japanese

- src/app/features/planner/dialog-schedule-task/dialog-schedule-task.component.html
- src/app/features/planner/dialog-schedule-task/dialog-schedule-task.component.ts
- src/app/features/tasks/task-context-menu/task-context-menu-inner/task-context-menu-inner.component.html
- src/app/features/tasks/task-context-menu/task-context-menu-inner/task-context-menu-inner.component.ts
- src/app/features/tasks/task/task-hover-controls/task-hover-controls.component.html
- src/app/features/tasks/task/task-hover-controls/task-hover-controls.component.ts
- src/app/features/tasks/task/task.component.html
- src/app/features/tasks/task/task.component.ts
- src/app/features/tasks/util/is-task-today.ts
This fix prevents the today tag to be added multiple times on the same task using the Context Menu and the Schedule Dialog.
https://github.com/johannesjo/super-productivity/issues/3518
> Bugfix: Prevent the Today tag to be added multiple times

- src/assets/i18n/en.json
- src/assets/i18n/fr.json
Add French missing translations
> Add French missing translations

- src/assets/i18n/es.json
add the translations of some words in the Spanish language
> Adding Missing translations (SPANISH)

- src/assets/i18n/fa.json
Helped with the Persian (Farsi) translation a little.
Preview the messages on https://inlang.com/github.com/inattentive-nerd/super-productivity .
> Update translations (Persian/Farsi)

- docker-compose.yaml
- nginx/default.conf.template
Fix #3686 .
It also fixes nginx issue on resolving webdav host name.
> fix: crash when env var WEBDAV_BACKEND is not set

- README.md
- android/README_OFFLINE.md
Fixed 2 dead links in README files.
> README files dead link minor fix

- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Themed icon
<details>
<summary>Images</summary>
</details>
#3672
> Themed icon

- README.md
Since the Android source code has moved location this PR updates the link in README.md.
> Update Android source code link in README.md

- README.md
Add mention of syncing to summary; I think it's one of the most useful features :grinning:
> Add mention of syncing to summary

- electron-builder.yaml
I believe this is a bit more specific than the existing `Utility`, based on https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html. These categories are what I put in the flatpak appstream. metadata file.
> Update Linux categories in electron-builder.yaml

- src/assets/i18n/tr.json
New PR due to failure in actions on #3826
> fix: add missing strings for tr.json

- README.md
- docs/concept/concept-for-2-file-sync.md
- docs/github-access-token-instructions.md
- electron/main-window.ts
- src/app/features/issue/providers/gitea/gitea-issue/gitea-issue-map.util.ts
- src/app/features/ui-helper/ui-helper.service.ts
- src/app/features/worklog/worklog-export/worklog-export.component.ts
- src/app/imex/sync/encryption.ts
- Adds docs on generating a GitHub token
- Improve GitLab token docs
- Fixes a few typos in comments
Helps prevent https://github.com/johannesjo/super-productivity/issues/3844
> improve documentation about GitHub tokens

- README.md
Update Twitter icon.
[List any existing issues this PR resolves](https://github.com/johannesjo/super-productivity/issues/3878)
> docs(README): update Twitter icon (#3878)

- src/assets/i18n/it.json
I have added 2 new translations and fixed other ones because some of these were translated into another language, maybe into arabian or turkish :-)
> Fixed and added new italian translations

- src/assets/i18n/tr.json
fix wrong variables on turkish translation
if `TOTAL: 408 SUCCESS` then
> fix: turkish translation

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Updates the bug report template to include extra log paths for snap and flatpak
None
> Update bug report template to include extra log paths on Linux

- src/app/features/work-view/work-view.component.ts
Ensure the detail panel closes when a scheduled (or removed) task no longer appears in today's list by automatically deselecting it. This resolves the issue where the detail panel remains stuck open after scheduling a task into the future.
If the user scheduled a task at a future time using the task detail panel and was on the today's tag page, the task would get removed from the list of tasks showing (done or undone) without being deselected, making it hard to close the task detail panel, since the task detail panel is exposed if there's a selected task. Example of behaviour (before):
This PR ensures that if a task is removed from the list of tasks showing, the code auto-deselects it, closing the task detail panel.
Example of current behaviour: …
> Fix #4014: auto-deselect task removed from current list

- src/app/imex/local-backup/local-backup.module.ts
- src/app/root-store/feature-stores.module.ts
Resolves #4137 as discussed in https://github.com/johannesjo/super-productivity/issues/4137#issuecomment-2764407589
> fix: LocalBackupService not instantiating #4137

- src/assets/i18n/it.json
I have updated only the italian translation on it.json file with the right strings.
> feat: updated italian translations

- src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts
If an issue is closed in Gitlab, it is also closed during synchronization
#3894
> feat: #3894 Add Gitlab close

- src/assets/i18n/tr.json
Improve the clarity and consistency of Turkish translations throughout the application.
> Update Turkish translations 

- .devcontainer/devcontainer.json
- README.md
Introduce a `devcontainer.json` file to enable development in GitHub Codespaces, allowing users to run a development version of Super Productivity directly in their browser without local setup, enabling people to contribute edits to the repository without having to install local dependencies. 
Update documentation to guide users on utilizing the dev container.
> chore: add support for github codespaces

- .devcontainer/devcontainer.json
- .vscode/extensions.json
This pull request introduces configuration updates to the development environment in devcontainers, preparing the image with a Chrome binary needed for tests, the git tool, and recommending a VS Code extension for testing and debugging tests.
> chore: add git and testing tools out of the box in devcontainers

- src/app/util/speak.ts
Rewrote the same logic. in a different way so it accounts for Safari strings for voice, which are then true when. find runs when the user changes voice option on safari browsers
This change allows users to succesful change voice from the Indian default to other voices in Domina. 
[#4782](https://github.com/johannesjo/super-productivity/issues/4782)
> fix(Domina): fix #4782 to allow domina mode to switch from an Indian accent to other accents in dropdown on safari browsers

- src/app/features/issue/issue.service.ts
Updated the regex for searching issues to include Unicode letters.
#4860
> Fix #4860: Unicode support in searching for issues

- src/assets/i18n/en.json
> fix a typo

- src/assets/i18n/tr.json
Include the Turkish translations that were previously missing to enhance localization support.
Note: Tests are only run on the development server due to auto-commit test issues. If passing automated tests is essential, I'll look into fixing the problems during my spare time.
Admittedly, my lack of knowledge about npm testing and TypeScript might be the cause. I may have missed necessary dependencies or configurations that are required for automated tests to run successfully.
```bash
[error] Error: Error in config file!
Error: Cannot find module 'karma-spec-reporter'
Require stack:
- /home/developer/Documents/global-repos/super-productivity/src/karma.conf.js
- /home/developer/Documents/global-repos/super-productivity/node_modules/karma/lib/config.js
- …
```
> feat(i18n): add missing turkish translations

- src/app/features/simple-counter/simple-counter-button/simple-counter-button.component.scss
Fix alignment in simple counter component
This fixes the alignment issue for emojis
Fixes #5131
> fix(simple-counter) : adjust mat-icon positioning for better alignment

- src/assets/i18n/ru.json
This changes improve the Russian translation of several UI strings to make them sound more natural and grammatically correct.
> Improve Russian translation for snooze and tracking

- src/app/pfapi/api/sync/providers/webdav/webdav-api.ts
fix webDAV sync failure by adding fallback for retrive Last-Modified and ETag info.
[5236](https://github.com/johannesjo/super-productivity/issues/5236)
> fix(webDAV): adding fallback option via PROPFIND for "Last-Modified" and "ETag" cache info
